### ISSUE TITLE
Builds error due to invalid default ArtifactsPublisher selection

### ISSUE THREAD

**Issue by rymancl** [whitesource/teamcity-plugin#3]
### Issue Description 
_Since TeamCity 2018.1 TeamCity comes bundled with [Amazon S3 Artifact Storage plugin](https://plugins.jetbrains.com/plugin/9623-aws-s3-artifact-storage) which allows storing build artifacts in an Amazon S3 bucket._ 

If this plugin is enabled, the Whitesource TeamCity plugin errors out because it chooses the first `ArtifactsPublisher.class` across all plugins that it finds, and does not do any validation against it. See **[WhitesourceLifeCycleListener.java L255](https://github.com/whitesource/teamcity-plugin/blob/master/agent/src/main/java/org/whitesource/teamcity/agent/WhitesourceLifeCycleListener.java#L255)**. I think this needs to not pick the first one it finds. 

We have this S3 plugin installed but it is not in use anywhere. The Whitesource plugin still tries to use it. I'm sure there are plenty of other plugins out there that are registered with `ArtifactsPublisher` as well that could run into this. 

### Error log
> [Step 3/8] Secret access key must not be empty
> S3 bucket name must not be empty
> AWS region must not be empty
> Access key ID must not be empty
> Credentials type must not be empty

### Temporary Resolution
We had to disable the S3 plugin on the server in order to get past this error in the Whitesource plugin.

Please let me know if you'd like any extra info. Thanks!

**Comment by ChenLuigi** [comment]
Hi @rymancl,

Thank you for your description and for opening this issue.
We opened an internal case in our system to identify and solve this error, in order to receive an update regarding this issue please contact with WhiteSource support for more details.
